#!/usr/bin/env bash
set -x

if [[ -z $STOW_FOLDERS ]]; then
    export STOW_FOLDERS="bin,kairion,personal,tmux,uwuntu,xkb,bash"
fi

if [[ -z $DOTFILES ]]; then
    export DOTFILES=$HOME/.dotfiles
fi

"$DOTFILES/install"
