#!/usr/bin/env bash
set -x

if [[ -z $STOW_FOLDERS ]]; then
    export STOW_FOLDERS="bash,bin,kairion,linux,personal,tmux,vault"
fi

if [[ -z $DOTFILES ]]; then
    export DOTFILES=$HOME/.dotfiles
fi

"$DOTFILES/install"
